{% set name = "hdmf_zarr" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3801d60d9f82ffd07cb3d25a9a5ec8b87dc5f23270bd8dac5ab075dd28f4d9b

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8
    - hdmf >=3.9.0
    - zarr >=2.11.0
    - numpy >=1.24
    - numcodecs >=0.9.1
    - pynwb >=2.5.0
    - threadpoolctl >=3.1.0

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - hdmf_zarr
  commands:
    - pytest -v

about:
  home: https://github.com/hdmf-dev/hdmf-zarr
  summary: Zarr backend for HDMF
  description: |
    The hdmf-zarr library implements a Zarr backend for HDMF as well
    as convenience classes for integration of Zarr with PyNWB to
    support writing of NWB files to Zarr.

  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://hdmf-zarr.readthedocs.io/en/latest/
  dev_url: https://github.com/hdmf-dev/hdmf-zarr/tree/dev/src/hdmf_zarr

extra:
  recipe-maintainers:
    - mavaylon1
