{% set name = "hdmf_zarr" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d22b344ef58b4fd685d5b15bc754572fd35f2d10a8b3619e5b59a528115f1fd

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - hdmf ==3.5.4
    - numpy <1.24
    - zarr >=2.11.0
    - numcodecs >=0.9.1
    - pynwb >=2.0.0
    - setuptools

test:
  commands:
    - pip check
  imports:
    - hdmf_zarr
  requires:
    - pip

about:
  home: https://github.com/hdmf-dev/hdmf-zarr
  summary: Zarr backend for HDMF
  description: |
    The hdmf-zarr library implements a Zarr backend for HDMF as well
    as convenience classes for integration of Zarr with PyNWB to
    support writing of NWB files to Zarr.

  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://hdmf-zarr.readthedocs.io/en/latest/
  dev_url: https://github.com/hdmf-dev/hdmf-zarr/tree/dev/src/hdmf_zarr

extra:
  recipe-maintainers:
    - mavaylon1
