{% set name = "hdmf_zarr" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c0312d869faa6a4427e6a0ba93f92daa0158a44436d6e28df7d3a8820e0b7445

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - hatchling
    - hatch-vcs
  run:
    - python >=3.9
    - hdmf >=3.14.5
    - zarr >=2.18.0, <3.0
    - numpy >=1.24.0
    - numcodecs >=0.10.0, <0.16.0
    - pynwb >=2.8.3
    - threadpoolctl >=3.1.0

test:
  source_files:
    - tests
  requires:
    - pytest
  imports:
    - hdmf_zarr
  commands:
    - pytest -v

about:
  home: https://github.com/hdmf-dev/hdmf-zarr
  summary: Zarr backend for HDMF
  description: |
    The hdmf-zarr library implements a Zarr backend for HDMF as well
    as convenience classes for integration of Zarr with PyNWB to
    support writing of NWB files to Zarr.

  license: BSD-3-Clause-LBNL
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://hdmf-zarr.readthedocs.io/en/latest/
  dev_url: https://github.com/hdmf-dev/hdmf-zarr/tree/dev/src/hdmf_zarr

extra:
  recipe-maintainers:
    - rly
    - mavaylon1
